### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by pandamasta** [AnalyseSI/AnalyseSI#15]
Impossible to run Analyse SI 0.76 on Debian 7.7 

Log
----
java -jar analyseSI-0.76.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/analyse/main/Main : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.analyse.main.Main. Program will exit.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

$java -version
java version "1.6.0_32"
OpenJDK Runtime Environment (IcedTea6 1.13.4) (6b32-1.13.4-1~deb7u1)
OpenJDK Server VM (build 23.25-b01, mixed mode)

**Comment by brunodabo** [comment]
Hello
Merci de cette contribution. Nous allons travailler sur cette anomalie
Cordialement


2015-01-13 17:06 GMT+01:00 Aurélien Martin <notifications@github.com>:

> Impossible to run Analyse SI 0.76 on Debian 7.7
> Log
>
> java -jar analyseSI-0.76.jar
> Exception in thread "main" java.lang.UnsupportedClassVersionError:
> org/analyse/main/Main : Unsupported major.minor version 51.0
> at java.lang.ClassLoader.defineClass1(Native Method)
> at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
> at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
> at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
> at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
> Could not find the main class: org.analyse.main.Main. Program will exit.
>
>
> $java -version
> java version "1.6.0_32"
> OpenJDK Runtime Environment (IcedTea6 1.13.4) (6b32-1.13.4-1~deb7u1)
> OpenJDK Server VM (build 23.25-b01, mixed mode)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AnalyseSI/AnalyseSI/issues/15>.
>



-- 
Bruno Dabo ( brunodabo@gmail.com )
M./ +33 6 23 86 46 00

**Comment by diskoekaterina** [comment]
Same problem with 1.6.0_65 java veriosn
